apiVersion: v1
kind: ServiceAccount
metadata:
  name: mls-server
  labels:
    app: mls-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mls-server-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mls-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mls-server-role
subjects:
  - kind: ServiceAccount
    name: mls-server
